name: Update RSS feed history
on:
  workflow_dispatch:
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run the main script
        run: python main.py
      - name: Commit the update
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add history.json
          git commit -m "Automatically updated history.json"
          git push
